- hosts: all
  become: yes
  tasks:
   - name: install APT Transport HTTPS
     apt:
       name: apt-transport-https
       state: present

   - name: install ca certificate 
     apt:
       name: ca-certificates
       state: present

   - name: install curl 
     apt:
       name: curl
       state: present

   - name: install gnupg-agent 
     apt:
       name: gnupg-agent
       state: present

   - name: install software-properties-common 
     apt:
       name: software-properties-common
       state: present

   - name: install pip3
     apt:
       name: python3-pip
       state: present

   - name: add docker apt-key
     apt_key:
       url: https://download.docker.com/linux/debian/gpg
       state: present

   - name: add docker's APT repository
     apt_repository:
      repo: deb https://download.docker.com/linux/debian stretch stable 
      state: present

   - name: Update apt and install docker-ce
     apt:
       update_cache: yes 
       name: docker-ce 
       state: latest

   - name: Install Docker Module for Python
     pip:
       name: docker
