- hosts: master
  become: yes
  tasks:
  - name: add nodejs apt-key
    apt_key:
      url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key 
      state: present

  - name: add nodejs's APT repository
    apt_repository:
      repo: "{{ item }}" 
      state: present
      filename: 'nodesource'
      update_cache: yes 
    with_items:
      - "deb http://deb.nodesource.com/node_11.x stretch main"
      - "deb-src https://deb.nodesource.com/node_11.x stretch main"
    
  - name: Update apt and install nodejs 
    apt:
      name: nodejs
      state: present    
