apiVersion: v1
kind: Namespace
metadata:
  name: web

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        command:
        - 'nginx'
        args: 
        - '-g'
        - 'daemon off;'
        - '-q'
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  labels:
    component: nginx-app
  name: nginx-svc
  namespace: web
spec:
  selector:
    app: nginx
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  type: NodePort
