
apiVersion: v1
kind: PersistentVolume
metadata:
  name: cockroachdb-pv
  labels:
    app: cockroachdb
spec:
  storageClassName: cockroachdb-sc
  local:
    path: /tmp
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values: 
          - docker-desktop
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 200M
---
apiVersion: v1
kind: Namespace
metadata:
  name: cockroachdb

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cockroachdb-sc
  labels:
    app: cockroachdb
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cockroachdb-pvc
  namespace: cockroachdb
  labels:
    app: cockroachdb
spec:
  storageClassName: cockroachdb-sc
  accessModes:
  - ReadWriteMany
  volumeName: cockroachdb-pv
  resources:
    requests:
      storage: 100M

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cockroachdb-svcacc
  namespace: cockroachdb
  labels:
    app: cockroachdb

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cockroachdb-role
  namespace: cockroachdb
  labels:
    app: cockroachdb
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - get

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cockroachdb-rolebinding
  namespace: cockroachdb
  labels:
    app: cockroachdb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cockroachdb-role
subjects:
- kind: ServiceAccount
  name: cockroachdb-svcacc
  namespace: cockroachdb

---
apiVersion: v1
kind: Service
metadata:
  name: cockroachdb-svc
  namespace: cockroachdb
  labels:
    app: cockroachdb
spec:
  selector:
    name: cockroachdb
  ports:
  - port: 26257
    targetPort: 26257
    protocol: TCP

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cockroachdb-ss
  namespace: cockroachdb
  labels:
    app: cockroachdb
spec:
  serviceName: cockroachdb-svc
  replicas: 1
  selector:
    matchLabels:
      name: cockroachdb
  template:
    metadata:
      name: cockroachdb
      namespace: cockroachdb
      labels:
        name: cockroachdb
        app: cockroachdb
    spec:
      #      serviceAccountName: cockroachdb-svcacc
      containers:
      - name: cockroachdb
        image: cockroachdb/cockroach:v20.2.3
        ports:
        - containerPort: 26257
        volumeMounts:
        - name: cockroach-volume
          mountPath: /export/cockroach

      volumes:
      - name: cockroach-volume
        persistentVolumeClaim:
          claimName: cockroachdb-pvc



