apiVersion: v1
kind: Namespace
metadata:
  name: mongodb

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mongodb-deployment
  name: mongodb-deployment
  namespace: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mongodb
    spec:
      containers:
      - image: mongo
        name: mongodb
        volumeMounts:
        - name: mongodb-disk
          mountPath: /export/mongodb
        - name: mongodb-conf
          mountPath: /export/mongodb/conf
        ports:
        - containerPort: 27017
      volumes:
      - name: mongodb-disk
        persistentVolumeClaim:
          claimName: mongodb-pvc

      - name: mongodb-conf
        configMap: 
          name: mongodb.conf

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: mongodb
  labels:
    app: mongodb
spec:
  selector:
    app: mongodb
  ports:
  - name: mongodb-port
    targetPort: 27017
    protocol: TCP
    port: 27017
  type: NodePort

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-conf
  namespace: mongodb
  labels:
    api: mongodb
data:

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb.conf
  namespace: mongodb
data:
  mongodb.conf: ""
