apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
  namespace: mongodb
  labels:
    app: api
spec:
  storageClassName: localdisk
  volumeName: api-persistance
#   selector:
#     matchLabels:
#       storage: api
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200M
