apiVersion: v1
kind: Namespace
metadata:
  name: redis

---



---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  namespace: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      name: redis
      labels:
        app: redis
      namespace: redis
    spec:
      containers:
      - image: redis
        name: redis
        command:
        - redis-server
        - "/redis/redis.conf"
        ports:
        - containerPort: 6379
        volumeMounts:
        - mountPath: /redis
          name: redis-volume
      volumes:
      - name: redis-volume
        configMap:
          name: redis-conf

---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: redis
spec:
  selector:
    app: redis
  ports:
  - port: 6379
    targetPort: 6379
